config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'inquiry' => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'
  get 'search/search'
  get 'search/not_search'
  resources :users, only:[:edit, :update]
  resources :groups, only:[:create, :index, :edit, :update, :destroy] do
  	resources :group_users, only:[:create, :index, :update, :destroy]
    get 'search/search_date'
  	resources :todolists do
  		resources :comments, only:[:create, :destroy]
  		resource :checks, only:[:create, :destroy]
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
	belongs_to :user
	belongs_to :todolist
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :todolist
	validates :comment, presence: true, length: {maximum: 100, minimum: 1}
end

app/models/group.rb
class Group < ApplicationRecord
	
	belongs_to :user
	has_many :group_users, dependent: :destroy
	has_many :todolists, dependent: :destroy

	enum group_key_flag: { 有効: true, 無効: false}

	validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
	belongs_to :user
	belongs_to :group
	enum join_status: { 参加する: 0, 参加申請中: 1, 参加中: 2}
	enum permit_status: { 許可: true, 拒否: false}
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/todolist.rb
class Todolist < ApplicationRecord
	
	belongs_to :group

	has_many :comments, dependent: :destroy
	has_many :checks, dependent: :destroy

	validates :head, presence: true

	def checked_by?(user)
    checks.where(user_id: user.id).exists?
  	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :group_users, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :checks, dependent: :destroy

    attachment :image

    validates :name, presence: true
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController #協力ボタン
	before_action :authenticate_user!
	def create
		@group = Group.find(params[:group_id])
		@todolist = Todolist.find(params[:todolist_id])
		check = current_user.checks.new(todolist_id: @todolist.id)
		check.save
	end
	def destroy
		@group = Group.find(params[:group_id])
		@todolist = Todolist.find(params[:todolist_id])
		check = current_user.checks.find_by(todolist_id: @todolist.id)
		check.destroy
	end
end

app/controllers/group_users_controller.rb
class GroupUsersController < ApplicationController
	before_action :authenticate_user!
	def index
		if Group.exists?(id: params[:group_id])
			@group = Group.find(params[:group_id])
			@group_users = GroupUser.where(group_id: @group.id).page(params[:page])
			group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
			if group_user.nil?
			redirect_to groups_path
			else
				if group_user.permit_status != "許可"
				redirect_to groups_path
				end
			end
		else
		redirect_to groups_path
		end
	end
	def create  #参加申請をしてきたユーザーの処理
		group = Group.find(params[:group_id])
		group_user = GroupUser.new
		group_user.user_id = current_user.id
		group_user.group_id = group.id
		group_user.permit_status = '拒否'
		group_user.join_status = '参加申請中'
		group_user.save!
		redirect_back(fallback_location: root_path)
	end
	def update
		group = Group.find(params[:group_id])
		group_user = GroupUser.find(params[:id])
		group_user.update(permit_status: '許可', join_status: '参加中')
		redirect_to group_group_users_path(group.id)
	end
	def destroy
		group_user = GroupUser.find(params[:id])
		group_user.destroy
		redirect_to groups_path
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :authenticate_user!
	def new
		@group = Group.new
	end
	def create
		@group = Group.new(group_params)
		@group.user_id = current_user.id
		if @group.save
		flash[:group_create] = "新たなグループを作成しました！"
		@group_user = GroupUser.new            #グループ作成者のグループユーザーのデータ作成
		@group_user.user_id = current_user.id
		@group_user.group_id = @group.id
		@group_user.permit_status = '許可'
		@group_user.join_status = '参加中'
		@group_user.save!
		redirect_to groups_path
		else
		@group_users = GroupUser.where(user_id: current_user.id, join_status: '参加中' ).page(params[:page]).per(12)
		render 'index'
		end
	end
	def index
		@group = Group.new
		@group_users = GroupUser.where(user_id: current_user.id, join_status: '参加中' ).page(params[:page]).per(12)
	end
	def edit
		if Group.exists?(id: params[:id])
			@group = Group.find(params[:id])
			group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
			unless group_user.nil?
				if  group_user.permit_status != "許可"
					redirect_to groups_path
				end
			else
			redirect_to groups_path
			end
		else
			redirect_to groups_path
		end
	end
	def update
		@group = Group.find(params[:id])
		if @group.update(group_params)
		flash[:group_update] = "グループを更新しました！"
		redirect_to group_todolists_path(@group)
		else
			render 'edit'
		end

	end
	def destroy
		@group = Group.find(params[:id])
		@group.destroy
		redirect_to groups_path
	end
	private
	def group_params
		params.require(:group).permit(:user_id, :name, :group_key_flag)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def edit
		if User.exists?(id: params[:id])
			@user = User.find(params[:id])
			if  @user != current_user
				redirect_to edit_user_path(current_user)
			end
		else
			redirect_to edit_user_path(current_user)
		end
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:user] = "ユーザーデータを更新しました！"
			redirect_to groups_path
		else
			render 'edit'
		end
	end
	private
	def user_params
		params.require(:user).permit(:name, :image, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/group_users/index.html.erb
<div class="container">
	<div class="row">
		<h2 class="col-xs-10">メンバー一覧</h2>
	</div>
	<div class="row">
		<table class="table table-hover">
			<% @group_users.each do |group_user| %>
			<tr>
				<td class="col-md-2">
					<%= attachment_image_tag group_user.user, :image, class: "img-square", fallback: "no_image.jpg", size:"50x50" %>
				</td>
				<td class="col-md-6">
					<%= group_user.user.name %>
				</td>
				<% if @group.user_id == current_user.id %>
					<% if group_user.user_id == current_user.id %>
						<td>
							<%= link_to "グループを削除する", group_path(@group.id), method: :delete, data: {confirm: "グループを削除してもよろしいですか？"}, class: "btn btn-lg" %>
						</td>
					<% elsif group_user.join_status == "参加申請中" && group_user.permit_status == "拒否" %>
						<td>
							<%= link_to "許可", group_group_user_path(@group.id, group_user.id), method: :put, class: "btn btn-default" %>
							<%= link_to "拒否", group_group_user_path(@group.id, group_user.id), method: :delete, data: {confirm: "参加を拒否しますか？"}, class: "btn btn-default" %>
						</td>
					<% else %>
						<td></td>
					<% end %>
				<% elsif group_user.user_id == current_user.id && @group.user_id != current_user.id %>
						<td>
							<%= link_to "グループから抜ける", group_group_user_path(@group.id, group_user.id), method: :delete, data: {confirm: "グループから抜けてよろしいですか？"}, class: "btn btn-lg" %>
						</td>
				<% else %>
					<td></td>
				<% end %>
			</tr>
			<% end %>
		</table>
		<div class="row">
			<%= link_to "戻る", group_todolists_path(@group.id), class: "btn btn-lg" %>
		</div>
	</div>
	<%= paginate @group_users %>
</div>

app/views/group_users/member.html.erb
<div class="container">
	<div class="row">
	<h2 class="col-xs-10">グループ一覧</h2>
	<%= link_to new_groups_path do %>
		<button class="btn-circle btn-lg" >＋</button>
	<% end %>
	</div>
	<div class="row">
		<table class="table table-hover">
			<thead>
			<tr>
				<th>グループID</th>
				<th>グループ名</th>
				<th>参加数</th>
			</tr>
			</thead>
			<tbody>
				<% @group_users.each do |group_user| %>
			<tr>
				<td><%= attachment_image_tag group_user.user, :image, class: "img-square", fallback: "no_image.jpg", size:"200x200" %></td>
				<td><%= group_user.user.name %></td>
				<td><%= form_for @roup_user, url: group_users_path do |f| %>
					<label><%= f.radio_button :group_status, "許可" ,checked: "checked"%>許可</label>
					<label><%= f.radio_button :group_status, "拒否" %>拒否</label>
					<%= f.submit "決定", class: "btn btn-primary" %>
					<% end %>
				</td>
			</tr>
				<% end %>
			</tbody>
		</table>
	</div>