config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'inquiry' => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'
  get 'search/search'
  get 'search/not_search'
  resources :users, only:[:edit, :update]
  resources :groups, only:[:create, :index, :edit, :update, :destroy] do
  	resources :group_users, only:[:create, :index, :update, :destroy]
    get 'search/search_date'
  	resources :todolists do
  		resources :comments, only:[:create, :destroy]
  		resource :checks, only:[:create, :destroy]
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
	belongs_to :user
	belongs_to :todolist
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :todolist
	validates :comment, presence: true, length: {maximum: 100, minimum: 1}
end

app/models/group.rb
class Group < ApplicationRecord
	
	belongs_to :user
	has_many :group_users, dependent: :destroy
	has_many :todolists, dependent: :destroy

	enum group_key_flag: { 有効: true, 無効: false}

	validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
	belongs_to :user
	belongs_to :group
	enum join_status: { 参加する: 0, 参加申請中: 1, 参加中: 2}
	enum permit_status: { 許可: true, 拒否: false}
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/todolist.rb
class Todolist < ApplicationRecord
	
	belongs_to :group

	has_many :comments, dependent: :destroy
	has_many :checks, dependent: :destroy

	validates :head, presence: true

	def checked_by?(user)
    checks.where(user_id: user.id).exists?
  	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :group_users, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :checks, dependent: :destroy

    attachment :image

    validates :name, presence: true
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController #協力ボタン
	before_action :authenticate_user!
	def create
		@group = Group.find(params[:group_id])
		@todolist = Todolist.find(params[:todolist_id])
		check = current_user.checks.new(todolist_id: @todolist.id)
		check.save
	end
	def destroy
		@group = Group.find(params[:group_id])
		@todolist = Todolist.find(params[:todolist_id])
		check = current_user.checks.find_by(todolist_id: @todolist.id)
		check.destroy
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	before_action :authenticate_user!
	def search_form
	end

	def search  #グループIDの検索
		content = params["search"]["content"]
		if Group.exists?(id: content)
		@group = Group.find_by(id: content)
		@group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
		else
			redirect_to search_not_search_path
		end
	end

	def not_search
		
	end
	def search_date  #日付検索
		date = params["search"]["date"]
		@today = Date.current
		if Group.exists?(id: params[:group_id])
			@group = Group.find(params[:group_id])
			@todolists = Todolist.where(group_id: @group.id, day: date).page(params[:page]).reverse_order
			group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
			if group_user.nil?
				redirect_to groups_path
			else
				if group_user.permit_status != "許可"
					redirect_to groups_path
				end
			end
		else
			redirect_to groups_path
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def edit
		if User.exists?(id: params[:id])
			@user = User.find(params[:id])
			if  @user != current_user
				redirect_to edit_user_path(current_user)
			end
		else
			redirect_to edit_user_path(current_user)
		end
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:user] = "ユーザーデータを更新しました！"
			redirect_to groups_path
		else
			render 'edit'
		end
	end
	private
	def user_params
		params.require(:user).permit(:name, :image, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/search/_search-date.html.erb
<div>
	<%= form_tag group_search_search_date_path(@group), :method => 'get' do %>
		<%= date_field_tag 'search[date]',"",class: "search_date-tag" %>
    	<%= submit_tag '検索', style: "background-color: white;" %>
    <% end %>
</div>

app/views/search/_search-form.html.erb
<div>
	<%= form_tag search_search_path,:method => 'get' do %>
		<%= text_field_tag 'search[content]',"", :placeholder => "グループID検索" ,class: "search-tag" %>
    	<%= submit_tag '検索', style: "background-color: #CCFFFF;" %>
    <% end %>
</div>

app/views/search/not_search.html.erb
<div class="container">
	<h3>検索結果</h3>
	<div class="row">
		<div class="text-center">
			<i class="fab fa-sistrix" style="font-size: 100px; color: gray;"></i>
		</div>
		<h3 class="text-center" style="color: gray;">一致するグループは見つかりませんでした。<br>
			検索したグループが存在しない、またはグループ作成者が検索を無効としています。</h3>
	</div>
	<div class="row">
		<%= link_to "戻る", :back, class: "btn btn-lg text-center" %>
	</div>
</div>

app/views/search/search.html.erb
<div class="container">
	<h3>検索結果</h3>
	<% if @group.group_key_flag == "有効" %>
	<div class="row">
		<table class="table table-striped">
			<tr>
				<th>グループID</th>
				<th>画像</th>
				<th>作成者</th>
				<th>グループ名</th>
				<th></th>
			</tr>
			<tr>
				<td><%= @group.id %></td>
				<td><%= attachment_image_tag @group.user, :image, fallback: "no_image.jpg", class:"search-image", size: "40x40" %></td>
				<td><%= @group.user.name %></td>
				<td><%= @group.name %></td>
				<% if @group.group_users.include?(@group_user) %>
					<% if @group_user.join_status == "参加中" %>
					<td><%= link_to "参加中", group_todolists_path(@group.id), class: "btn btn-default" %></td>
					<% else %>
					<td><%= @group_user.join_status %></td>
					<% end %>
				<% else %>
				<td>
					<%= link_to "参加する",group_group_users_path(@group.id), method: :post, class: "btn btn-default" %>
				</td>
				<% end %>
			</tr>
		</table>
	</div>
	<% else %>
	<div class="row">
		<div class="text-center">
			<i class="fab fa-sistrix" style="font-size: 100px; color: gray;"></i>
		</div>
		<h3 class="text-center" style="color: gray;">一致するグループは見つかりませんでした。<br>
		検索したグループが存在しない、またはグループ作成者が検索無効としています。</h3>
	</div>
	<% end %>
	<div class="row">
		<%= link_to "戻る", groups_path, class: "btn btn-lg text-center"%>
	</div>
</div>

app/views/search/search_date.html.erb
<div class="container">
	<h1><%= @group.name %></h1>
		<%= render partial: 'search/search-date' %>
    	<br>
	<div class="row">
		<%= link_to "メンバー一覧", group_group_users_path(@group.id), class: "btn btn-default col-md-2" %>
		<% if @group.user_id == current_user.id %>
			<%= link_to "グループ編集", edit_group_path(@group.id), class: "btn btn-default col-md-2" %>
			<%= link_to "グループ削除", group_path(@group.id), method: :delete, data: {confirm: "グループを削除してもよろしいですか？"}, class: "btn btn-default col-md-2" %>
			<div class="col-md-4"></div>
		<% else %>
			<div class="col-md-8"></div>
		<% end %>
			<%= link_to "＋TODOリスト作成",new_group_todolist_path(@group.id),class: "btn btn-default col-md-2" %>
	</div>
	<% if @todolists.exists? %>
		<div class="row">
			<table class="table table-hover">
				<% @todolists.each_with_index do |todolist, i| %>
				<tr>
					<td class="col-md-1" data-todoid=<%= i %>><button>+</button></td>
					<td class="col-md-5"><%= link_to todolist.head, group_todolist_path(@group.id, todolist.id), style: "color: black;" %></td>
					<td class="col-md-1"><h5><%= todolist.day %></h5></td>
					<td class="col-md-1" id="check-<%= todolist.id %>">
					<%= render partial: 'checks/check', locals: { group: @group, todolist: todolist} %>
					</td>
					<td class="col-md-1 comment-count"><h5>コメント数<%= todolist.comments.count %></h5></td>
					<td class="col-md-2"><%= link_to "詳細", group_todolist_path(@group.id, todolist.id), class: "btn btn-default" %>
					<%= link_to "編集", edit_group_todolist_path(@group.id, todolist.id), class: "btn btn-default" %>
					<%= link_to "削除", group_todolist_path(@group.id, todolist.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-default" %>
					</td>
				</tr>
				<tr class="todolist_body todobody<%= i %>">
					<td class="todolist_body todobody<%= i %>" colspan="6"><%=  simple_format(todolist.body) %></td>
				</tr>
				<% end %>
				<%= paginate @todolists %>
			</table>
		</div>
	<% else %>
		<div class="row">
			<div class="todolists-text">
				<i class="fab fa-sistrix" style="font-size: 100px; color: gray;" ></i>
			</div>
			<h3 class="todolists-text" style="color: gray;">
				検索した日付でのTODOリストは<br>
				見つかりませんでした。</h3>
		</div>
	<% end %>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
	<div class="row">
		<%= link_to "戻る", group_todolists_path(@group), class: "btn btn-lg" %>
	</div>
</div>
<script>
	$(function() {
		$('.todolist_body').hide();
		$('button').on('click', function(){
			var todoid = $(this).parent().data().todoid;
			$('.todobody' + todoid).fadeToggle();
		});
	});
</script>