config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'inquiry' => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'
  get 'search/search'
  get 'search/not_search'
  resources :users, only:[:edit, :update]
  resources :groups, only:[:create, :index, :edit, :update, :destroy] do
  	resources :group_users, only:[:create, :index, :update, :destroy]
    get 'search/search_date'
  	resources :todolists do
  		resources :comments, only:[:create, :destroy]
  		resource :checks, only:[:create, :destroy]
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
	belongs_to :user
	belongs_to :todolist
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :todolist
	validates :comment, presence: true, length: {maximum: 100, minimum: 1}
end

app/models/group.rb
class Group < ApplicationRecord
	
	belongs_to :user
	has_many :group_users, dependent: :destroy
	has_many :todolists, dependent: :destroy

	enum group_key_flag: { 有効: true, 無効: false}

	validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
	belongs_to :user
	belongs_to :group
	enum join_status: { 参加する: 0, 参加申請中: 1, 参加中: 2}
	enum permit_status: { 許可: true, 拒否: false}
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/todolist.rb
class Todolist < ApplicationRecord
	
	belongs_to :group

	has_many :comments, dependent: :destroy
	has_many :checks, dependent: :destroy

	validates :head, presence: true

	def checked_by?(user)
    checks.where(user_id: user.id).exists?
  	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :group_users, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :checks, dependent: :destroy

    attachment :image

    validates :name, presence: true
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController #協力ボタン
	before_action :authenticate_user!
	def create
		@group = Group.find(params[:group_id])
		@todolist = Todolist.find(params[:todolist_id])
		check = current_user.checks.new(todolist_id: @todolist.id)
		check.save
	end
	def destroy
		@group = Group.find(params[:group_id])
		@todolist = Todolist.find(params[:todolist_id])
		check = current_user.checks.find_by(todolist_id: @todolist.id)
		check.destroy
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :authenticate_user!
	def new
		@group = Group.new
	end
	def create
		@group = Group.new(group_params)
		@group.user_id = current_user.id
		if @group.save
		flash[:group_create] = "新たなグループを作成しました！"
		@group_user = GroupUser.new            #グループ作成者のグループユーザーのデータ作成
		@group_user.user_id = current_user.id
		@group_user.group_id = @group.id
		@group_user.permit_status = '許可'
		@group_user.join_status = '参加中'
		@group_user.save!
		redirect_to groups_path
		else
		@group_users = GroupUser.where(user_id: current_user.id, join_status: '参加中' ).page(params[:page]).per(12)
		render 'index'
		end
	end
	def index
		@group = Group.new
		@group_users = GroupUser.where(user_id: current_user.id, join_status: '参加中' ).page(params[:page]).per(12)
	end
	def edit
		if Group.exists?(id: params[:id])
			@group = Group.find(params[:id])
			group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
			unless group_user.nil?
				if  group_user.permit_status != "許可"
					redirect_to groups_path
				end
			else
			redirect_to groups_path
			end
		else
			redirect_to groups_path
		end
	end
	def update
		@group = Group.find(params[:id])
		if @group.update(group_params)
		flash[:group_update] = "グループを更新しました！"
		redirect_to group_todolists_path(@group)
		else
			render 'edit'
		end

	end
	def destroy
		@group = Group.find(params[:id])
		@group.destroy
		redirect_to groups_path
	end
	private
	def group_params
		params.require(:group).permit(:user_id, :name, :group_key_flag)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
	before_action :authenticate_user!
	before_action :group_exists, only: [:new, :index, :show, :edit]  #存在しないグループのときに拒否する
	def new
		@todolist = Todolist.new
		@group = Group.find(params[:group_id])
		group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
		if group_user.nil?
			redirect_to groups_path
		else
			if  group_user.permit_status != "許可"
				redirect_to groups_path
			end
		end
	end
	def create
		@group = Group.find(params[:group_id])
		@todolist = Todolist.new(todolist_params)
		@todolist.group_id = @group.id
		if @todolist.save
			flash[:todolist] = "TODOリストを作成しました！"
		redirect_to group_todolists_path(@group)
		else
			render 'new'
		end
	end
	def index
		@today = Date.current
		@group = Group.find(params[:group_id])
		@todolists = Todolist.where(group_id: @group).page(params[:page]).reverse_order
		group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
		if group_user.nil?
			redirect_to groups_path
		else
			if group_user.permit_status != "許可"
				redirect_to groups_path
			end
		end
	end
	def show
		@group = Group.find(params[:group_id])
		group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
		@todolist = Todolist.find_by(group_id: @group.id, id: params[:id])
		unless @todolist.nil?
			@comments = Comment.where(todolist_id: @todolist.id).reverse
			@comment = Comment.new
			if  group_user.permit_status != "許可"
				redirect_to groups_path
			end
		else
			redirect_to groups_path
		end
	end
	def edit
		@group = Group.find(params[:group_id])
		group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
		@todolist = Todolist.find_by(group_id: @group.id, id: params[:id])
		if @todolist.nil?
			redirect_to groups_path
		else
			if  group_user.permit_status != "許可"
				redirect_to groups_path
			end
		end
	end
	def update
		@todolist = Todolist.find(params[:id])
		group_id = @todolist.group_id
		if @todolist.update(todolist_params)
			flash[:todolist] = "TODOリストを更新しました！"
		   redirect_to group_todolists_path(group_id)
		else
			@group = Group.find(params[:group_id])
			render 'edit'
		end
	end
	def destroy
		@todolist = Todolist.find(params[:id])
		group_id = @todolist.group_id
		@todolist.destroy
		redirect_to group_todolists_path(group_id)
	end
	private
	def todolist_params
	params.require(:todolist).permit(:group_id, :head, :body, :day)
	end
	def group_exists
		unless Group.exists?(id: params[:group_id])
			redirect_to groups_path
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def edit
		if User.exists?(id: params[:id])
			@user = User.find(params[:id])
			if  @user != current_user
				redirect_to edit_user_path(current_user)
			end
		else
			redirect_to edit_user_path(current_user)
		end
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:user] = "ユーザーデータを更新しました！"
			redirect_to groups_path
		else
			render 'edit'
		end
	end
	private
	def user_params
		params.require(:user).permit(:name, :image, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/todolists/edit.html.erb
<div class="container">
	<h3>編集</h3>
	<div class="row">
		<%= form_for @todolist, url: group_todolist_path do |f| %>
				<% if @todolist.errors.any? %>
			  		<h2><%= pluralize(@todolist.errors.count,"つエラーがあります") %></h2>
			  		<% @todolist.errors.full_messages.each do |message| %>
			  		<li><%= message %></li>
			   		<% end %>
				<% end %>
		<div class="todolist_edit-form">
			<div class="col-sm-12">
				<%= f.label :日付, class: "col-sm-1" %>
				<%= f.date_field :day, class: "col-sm-6" %>
			</div>
		</div>
		<div class="todolist_edit-form">
			<div class="col-sm-12">
				<%= f.label :タイトル, class: "col-sm-1" %>
				<%= f.text_field :head, class: "col-sm-6" %>
				<a class="col-xs-1" id="todolist-edit-button" style="color: black; font-size: 21px; cursor: pointer;">＋</a>
			</div>
		</div>
		<div class="todolist_edit-form" id="todolist-edit">
			<div class="col-sm-12">
				<%= f.label :内容, class: "col-sm-1" %>
				<%= f.text_area :body, class: "col-sm-6",style: "height: 200px;" %>
			</div>
		</div>
		<div class="todolist_edit-form">
			<div class="col-sm-12"><br>
				<div class="col-sm-1"></div>
				<%= f.submit "更新", class: "btn btn-default" %>
			</div>
		</div>
		<% end %>
	</div>
	<div class="row">
		<%= link_to "戻る", group_todolists_path(@group.id), class: "btn btn-lg" %>
	</div>
</div>
<script>
	$(function() {
		$('#todolist-edit').hide();
		$('#todolist-edit-button').on('click', function(){
			$('#todolist-edit').toggleClass('active');
			$('#todolist-edit').slideToggle();
		});
	});
</script>

app/views/todolists/index.html.erb
<div class="container">
	<% if flash[:todolist] %>
      <div class="flash">
        <%= flash[:todolist] %>
      </div>
    <% end %>
    <% if flash[:group_update] %>
      <div class="flash">
        <%= flash[:group_update] %>
      </div>
    <% end %>
    <h1><%= @group.name %></h1>
    <%= render partial: 'search/search-date' %>
    <br>
	<div class="row">
		<%= link_to "メンバー一覧", group_group_users_path(@group.id), class: "btn btn-default col-md-2" %>
			<% if @group.user_id == current_user.id %>
				<%= link_to "グループ編集", edit_group_path(@group.id), class: "btn btn-default col-md-2" %>
				<%= link_to "グループ削除", group_path(@group.id), method: :delete, data: {confirm: "グループを削除してもよろしいですか？"}, class: "btn btn-default col-md-2" %>
				<div class="col-md-4"></div>
			<% else %>
				<div class="col-md-8"></div>
			<% end %>
				<%= link_to "＋TODOリスト",new_group_todolist_path(@group.id),class: "btn btn-default col-md-2" %>
	</div>
	<% if @todolists.exists? %>
	<div class="row">
		<table class="table table-hover">
			<% @todolists.each_with_index do |todolist, i| %>
			<tr>
				<td class="col-md-1" data-todoid=<%= i %>><button>+</button></td>
				<td class="col-md-5"><%= link_to todolist.head, group_todolist_path(@group.id, todolist.id), style: "color: black;" %></td>
				<% unless todolist.day.nil? %>
					<% if (todolist.day-@today).numerator < 0 %>
						<td class="col-md-1"><h5><%= ((todolist.day-@today).numerator)*(-1) %>日超過</h5></td>
					<% elsif (todolist.day-@today).numerator == 0 %>
						<td class="col-md-1"><h5>本日</h5></td>
					<% elsif (todolist.day-@today).numerator > 0 %>
						<td class="col-md-1"><h5>あと<%= (todolist.day-@today).numerator %>日</h5></td>
					<% end %>
				<% else %>
					<td class="col-md-1"></td>
				<% end %>
					<td class="col-md-1" id="check-<%= todolist.id %>">
					<%= render partial: 'checks/check', locals: { group: @group, todolist: todolist} %>
					</td>
					<td class="col-md-1 comment-count"><h5>コメント数<%= todolist.comments.count %></h5></td>
					<td class="col-md-2"><%= link_to "詳細", group_todolist_path(@group.id, todolist.id), class: "btn btn-default" %>
					<%= link_to "編集", edit_group_todolist_path(@group.id, todolist.id), class: "btn btn-default" %>
					<%= link_to "削除", group_todolist_path(@group.id, todolist.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-default" %>
					</td>
			</tr>
			<tr class="todolist_body todobody<%= i %>">
				<td class="todolist_body todobody<%= i %>" colspan="6"><%= simple_format(todolist.body) %></td>
			</tr>
			<% end %>
			<%= paginate @todolists %>
		</table>
	</div>
	<% else %>
		<div class="row">
			<div class="todolists-text">
				<i class="fas fa-book-open" style="font-size: 100px; color: gray;" ></i>
			</div>
			<h3 class="todolists-text" style="color: gray;">
				＋TODOリストボタンを押して<br>
				新しいTODOリストを作成しましょう!</h3>
		</div>
	<% end %>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
	<div class="row">
		<%= link_to "戻る", groups_path, class: "btn btn-lg" %>
	</div>
</div>
	<script>
		$(function() {
			$('.todolist_body').hide();
			$('button').on('click', function(){
				var todoid = $(this).parent().data().todoid;
				$('.todobody' + todoid).fadeToggle();
			});
		});
	</script>

app/views/todolists/new.html.erb
<div class="container">
	<h2>todolist作成</h2>
	<div class="row">
		<%= form_for @todolist,url: group_todolists_path do |f| %>
			<% if @todolist.errors.any? %>
			  	<h2><%= pluralize(@todolist.errors.count,"つエラーがあります") %></h2>
			  	<% @todolist.errors.full_messages.each do |message| %>
			  		<li><%= message %></li>
			   	<% end %>
			<% end %>
		<div class="todolist_new-form">
			<div class="col-xs-12">
				<%= f.label :日付, class: "col-xs-1" %>
				<%= f.date_field :day, class: "col-xs-6" %>
			</div>
		</div>
		<div class="todolist_new-form">
			<div class="col-xs-12">
				<%= f.label :タイトル, class: "col-xs-1" %>
				<%= f.text_field :head, class: "col-xs-6" %>
				<a class="col-xs-1" id="todolist-new-button" style="color: black; font-size: 21px; cursor: pointer;">＋</a>
			</div>
		</div>
		<div class="todolist_new-form" id="todolist-new">
			<div class="col-xs-12">
				<%= f.label :内容, class: "col-xs-1" %>
				<%= f.text_area :body, class: "col-xs-6",style: "height: 200px;" %>
			</div>
		</div>
		<div class="todolist_new-form">
			<div class="col-xs-12"><br>
				<div class="col-xs-1"></div>
				<%= f.submit "作成", class: "btn btn-default" %>
			</div>
		</div>
		<% end %>
	</div>
	<div class="row">
		<%= link_to "戻る", group_todolists_path(@group.id), class: "btn btn-lg" %>
	</div>
</div>
<script>
	$(function() {
		$('#todolist-new').hide();
		$('#todolist-new-button').on('click', function(){
			$('#todolist-new').toggleClass('active');
			$('#todolist-new').slideToggle();
		});
	});
</script>

app/views/todolists/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-5">
			<h1 class="todolist-title"><%= @todolist.head %></h1><br>
				<% unless @todolist.day.nil? %>
					<h3 class="todolist-day">日付　<%= @todolist.day %></h3><br>
				<% end %>
				<h3 class="todolist-body"><%= simple_format(@todolist.body) %></h3>
				<br>
				<%= form_with(model: [@todolist, @comment], url:  group_todolist_comments_path(@group.id, @todolist.id)) do |f| %>
					<div class="comment-form">
					<% if @comment.errors.any? %>
			  			<h2><%= pluralize(@comment.errors.count,"つエラーがあります") %></h2>
			  			<% @comment.errors.full_messages.each do |message| %>
			  				<li><%= message %></li>
			   			<% end %>
					<% end %>
					<%= f.text_area :comment, style: "height: 60px; width: 60%;" %>
					</div>
				<div class="comment-form">
					<%= f.submit "コメントする", class: "btn btn-default",style: "width: 60%;" %>
				</div>
				<% end %>
			<div><br>
				<%= link_to "戻る", group_todolists_path(@group.id), class: "btn btn-lg" %>
			</div>
		</div>
		<div class="col-md-7">
			<div style="height: 850px; overflow-y:scroll;">
			<%= render partial: 'comments/comment', locals: { comments: @comments } %>
			</div>
		</div>
	</div>
</div>