config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'inquiry' => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'
  get 'search/search'
  get 'search/not_search'
  resources :users, only:[:edit, :update]
  resources :groups, only:[:create, :index, :edit, :update, :destroy] do
  	resources :group_users, only:[:create, :index, :update, :destroy]
    get 'search/search_date'
  	resources :todolists do
  		resources :comments, only:[:create, :destroy]
  		resource :checks, only:[:create, :destroy]
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
	belongs_to :user
	belongs_to :todolist
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :todolist
	validates :comment, presence: true, length: {maximum: 100, minimum: 1}
end

app/models/group.rb
class Group < ApplicationRecord
	
	belongs_to :user
	has_many :group_users, dependent: :destroy
	has_many :todolists, dependent: :destroy

	enum group_key_flag: { 有効: true, 無効: false}

	validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
	belongs_to :user
	belongs_to :group
	enum join_status: { 参加する: 0, 参加申請中: 1, 参加中: 2}
	enum permit_status: { 許可: true, 拒否: false}
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/todolist.rb
class Todolist < ApplicationRecord
	
	belongs_to :group

	has_many :comments, dependent: :destroy
	has_many :checks, dependent: :destroy

	validates :head, presence: true

	def checked_by?(user)
    checks.where(user_id: user.id).exists?
  	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :group_users, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :checks, dependent: :destroy

    attachment :image

    validates :name, presence: true
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController #協力ボタン
	before_action :authenticate_user!
	def create
		@group = Group.find(params[:group_id])
		@todolist = Todolist.find(params[:todolist_id])
		check = current_user.checks.new(todolist_id: @todolist.id)
		check.save
	end
	def destroy
		@group = Group.find(params[:group_id])
		@todolist = Todolist.find(params[:todolist_id])
		check = current_user.checks.find_by(todolist_id: @todolist.id)
		check.destroy
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :authenticate_user!
	def new
		@group = Group.new
	end
	def create
		@group = Group.new(group_params)
		@group.user_id = current_user.id
		if @group.save
		flash[:group_create] = "新たなグループを作成しました！"
		@group_user = GroupUser.new            #グループ作成者のグループユーザーのデータ作成
		@group_user.user_id = current_user.id
		@group_user.group_id = @group.id
		@group_user.permit_status = '許可'
		@group_user.join_status = '参加中'
		@group_user.save!
		redirect_to groups_path
		else
		@group_users = GroupUser.where(user_id: current_user.id, join_status: '参加中' ).page(params[:page]).per(12)
		render 'index'
		end
	end
	def index
		@group = Group.new
		@group_users = GroupUser.where(user_id: current_user.id, join_status: '参加中' ).page(params[:page]).per(12)
	end
	def edit
		if Group.exists?(id: params[:id])
			@group = Group.find(params[:id])
			group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
			unless group_user.nil?
				if  group_user.permit_status != "許可"
					redirect_to groups_path
				end
			else
			redirect_to groups_path
			end
		else
			redirect_to groups_path
		end
	end
	def update
		@group = Group.find(params[:id])
		if @group.update(group_params)
		flash[:group_update] = "グループを更新しました！"
		redirect_to group_todolists_path(@group)
		else
			render 'edit'
		end

	end
	def destroy
		@group = Group.find(params[:id])
		@group.destroy
		redirect_to groups_path
	end
	private
	def group_params
		params.require(:group).permit(:user_id, :name, :group_key_flag)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	before_action :authenticate_user!
	def search_form
	end

	def search  #グループIDの検索
		content = params["search"]["content"]
		if Group.exists?(id: content)
		@group = Group.find_by(id: content)
		@group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
		else
			redirect_to search_not_search_path
		end
	end

	def not_search
		
	end
	def search_date  #日付検索
		date = params["search"]["date"]
		@today = Date.current
		if Group.exists?(id: params[:group_id])
			@group = Group.find(params[:group_id])
			@todolists = Todolist.where(group_id: @group.id, day: date).page(params[:page]).reverse_order
			group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
			if group_user.nil?
				redirect_to groups_path
			else
				if group_user.permit_status != "許可"
					redirect_to groups_path
				end
			end
		else
			redirect_to groups_path
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def edit
		if User.exists?(id: params[:id])
			@user = User.find(params[:id])
			if  @user != current_user
				redirect_to edit_user_path(current_user)
			end
		else
			redirect_to edit_user_path(current_user)
		end
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:user] = "ユーザーデータを更新しました！"
			redirect_to groups_path
		else
			render 'edit'
		end
	end
	private
	def user_params
		params.require(:user).permit(:name, :image, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checks/_check.html.erb
<% if todolist.checked_by?(current_user)%>
	<%= link_to group_todolist_checks_path(group.id, todolist.id), method: :delete, class: "interpreting-button", remote: true do %>
			<i class="fas fa-american-sign-language-interpreting fa-fw fa-2x" style="color: red;" ></i>
	<% end %>
		<%= todolist.checks.count %>人参加
<% else %>
	<%= link_to group_todolist_checks_path(group.id, todolist.id), method: :post, class: "interpreting-button", remote: true do %>
			<i class="fas fa-american-sign-language-interpreting fa-fw fa-2x" aria-hidden="true"></i>
	<% end %>
			<%= todolist.checks.count %>人参加
<% end %>

app/views/checks/create.js.erb
$("#check-<%= @todolist.id %>").html('<%= escape_javascript(render("checks/check", group: @group, todolist: @todolist)) %>');

app/views/checks/destroy.js.erb
$("#check-<%= @todolist.id %>").html('<%= escape_javascript(render("checks/check", group: @group, todolist: @todolist)) %>');

app/views/groups/_new.html.erb
<%= form_for @group, url: groups_path do |f| %>
	<% if @group.errors.any? %>
		<h2><%= pluralize(@group.errors.count,"つエラーがあります") %></h2>
		<% @group.errors.full_messages.each do |message| %>
			  <li><%= message %></li>
		<% end %>
	<% end %>
	<%= f.label :グループ名 %>
	<%= f.text_field :name %>
	<%= f.label :　グループ検索 %>
	<label><%= f.radio_button :group_key_flag, "有効" ,checked: "checked"%> 有効 </label>
	<label><%= f.radio_button :group_key_flag, "無効" %> 無効</label>
	<%= f.label :　%>
	<%= f.submit "グループ新規作成", class: "btn btn-default" %>
<% end %>

app/views/groups/edit.html.erb
<div class="container">
	<h3>グループ編集</h3>
	<div class="row">
		<%= form_for @group, url: group_path do |f| %>
			<% if @group.errors.any? %>
			  	<h2><%= pluralize(@group.errors.count,"つエラーがあります") %></h2>
			  	<% @group.errors.full_messages.each do |message| %>
			  		<li><%= message %></li>
			   	<% end %>
			<% end %>
			<%= f.label :グループ名 %>
			<%= f.text_field :name %>
			<%= f.label :　グループ検索 %>
			<label><%= f.radio_button :group_key_flag, "有効" %> 有効 </label>
			<label><%= f.radio_button :group_key_flag, "無効" %> 無効</label>
			<%= f.label :　%>
			<%= f.submit "更新", class: "btn btn-default" %>
		<% end %>
	</div>
	<div class="row">
		<%= link_to "戻る", group_todolists_path(@group.id),class: "btn btn-lg" %>
	</div>
</div>

app/views/groups/index.html.erb
<div class="container">
	<% if flash[:group_create] %>
      <div class="flash">
        <%= flash[:group_create] %>
      </div>
    <% end %>
    <% if flash[:user] %>
      <div class="flash">
        <%= flash[:user] %>
      </div>
    <% end %>
	<div class="row">
		<h2 class="col-md-3">グループ一覧</h2>
		<div class="col-md-7"><br>
		<span id="group-new"><%= render partial: 'groups/new' %>
		</span>
		</div>
		<div class="col-md-2"><br>
			<a class= "btn btn-default" id="group-new-button">＋グループ</a>
		</div>
	</div>
	<% if @group_users.exists? %>
		<div class="row">
			<% @group_users.each do |group_user| %>
			<div class="col-md-4 group-box">
				<div class="clearfix">
					<div class="col-md-12" style="border: 1px solid;">
						<div class="col-md-4">
							<%= attachment_image_tag group_user.group.user, :image, :fill, 120, 140, fallback:  "no_image.jpg",size:"120x140", class: "group-image" %>
						</div>
						<div class="col-md-8 group-introduce"><br>
							<div>作成者：<%= group_user.group.user.name.truncate(10) %>
							</div>
							<div>グループID：<%= group_user.group.id %>
							</div>
							<div>グループ：<%= group_user.group.name.truncate(10) %>
							</div>
							<div>参加数：<%= group_user.group.group_users.count %>人
							</div>
							<div><%= link_to "詳細", group_todolists_path(group_user.group.id),class: "btn btn-default" %></div>
						</div>
					</div>
				</div>
			</div>
		<% end %>
		<%= paginate @group_users %>
		<% else %>
		<div>
			<div class="text-center">
				<i class="fas fa-hands-helping" style="font-size: 100px; color: gray;" ></i>
			</div>
			<h3 class="text-center" style="color: gray;">＋グループボタンを押して<br>
			新しいグループを作成しましょう！</h3>
		</div>
		<% end %>
	</div>
</div>
<script>
  $(function() {
  $('#group-new').hide();
  $('#group-new-button').on('click', function(){
    $('#group-new').toggleClass('active');
    $('#group-new').fadeToggle();
  });
});
</script>

app/views/users/edit.html.erb
<div class="container">
	<h2>ユーザー編集</h2>
		<%= form_for @user do |f| %>
			<% if @user.errors.any? %>
			  	<h2><%= pluralize(@user.errors.count,"つエラーがあります") %></h2>
			  	<% @user.errors.full_messages.each do |message| %>
			  		<li><%= message %></li>
			   	<% end %>
			<% end %>
			<div class="row profile">
				<div class="col-md-4">
					<%= attachment_image_tag @user, :image, class: "img-square", fallback: "no_image.jpg", size:"200x200" %>
					<%= f.label :イメージ画像 %>
					<%= f.attachment_field :image %>
				</div>
				<div class="col-md-8">
					<div>
						<%= f.label :ユーザーネーム %>
						<%= f.text_field :name %>
					</div>
					<br>
					<div>
						<%= f.label :メールアドレス %>
						<%= f.email_field :email, autofocus: true, autocomplete: "email" %>
					</div>
				</div>
			</div>
	<script>
		$(function(){
    		$('.profile').on('change', function (e) {
				var reader = new FileReader();
				reader.onload = function (e) {
				$(".image").attr('src', e.target.result);
				}
    			reader.readAsDataURL(e.target.files[0]);
			});
		});
	</script>
<div class="row">
	<div class="col-xs-6"></div>
		<%= f.submit "ユーザー情報更新" ,class: "btn btn-default"%>
</div>
		<% end %>
	<div class="row">
		<%= link_to "戻る", groups_path,class: "btn btn-lg" %>
	</div>
</div>